### ISSUE TITLE
Thank you for your work.Could you provide the older version of the repo to extract features

### ISSUE THREAD

**Issue by a1391651300** [salesforce/densecap#25]
Thank you for your work . You have said "Note that ActivityNet is processed with an older version of the repo while YouCook2 is processed with the latest code which had a minor change regarding the sampling approach. This accounts for the difference in the formulation of frame_to_second conversion."
Could you provide the older version of the repo to extract features?Or could I  extract features of ActivityNet with the latest code and using the features by the same way of yc2 dataset  without  flooring the rate?

**Comment by LuoweiZhou** [comment]
The only differences are the two: [frame_interval](https://github.com/LuoweiZhou/anet2016-cuhk-feature/commit/357dc8ed5bc13c5cee4585a04f59f9208a5291d3#r35634942) and [duration casting](https://github.com/LuoweiZhou/anet2016-cuhk-feature/commit/372bf16a7dd9508c740ee847809810e7876d2845). The first one is the major one.

If you extract features on ActivityNet with the newer version, the pre-trained model might not work as well as before due to the discrepancy in the video sampling rate.

**Comment by a1391651300** [comment]
Thank you so much.
