### ISSUE TITLE
How to generate captions for GT segments?

### ISSUE THREAD

**Issue by n4r3n00** [salesforce/densecap#42]
From the code and github readme, those codes seem to generate the captions only for learned proposals.
(In github, "We use a different code base for captioning-only models (dense captioning on GT segments). ")
Can I know how to generate the captions for GT segments?
Can you share any code or idea to do that?

**Comment by LuoweiZhou** [comment]
@n4r3n00 That part of code has not been sanitized or reviewed yet and hence we are not planning for a release. To adapt the existing code to captioning-only, you will need to feed GT windows rather than generated proposals to the Transformer decoder. The proposal module will no longer be needed and the resulted code will be quite light-weight. Please refer to action_prop_dense_cap.py and transformer.py for details.
