### ISSUE TITLE
What does downsampling every 0.5 seconds mean?

### ISSUE THREAD

**Issue by asafarevich** [salesforce/densecap#5]
I still have a question about this issue, https://github.com/salesforce/densecap/issues/3.
However, piggybacking of the link provided.
Due to "downsampling every 0.5 seconds", does the video extraction models need to be retrained?
I did not see in paper for the linked repo any mentioning of downsampling at 0.5sec.

Also not sure what you mean by the time. Say the video is 30 fps. Does that mean you take 2 frames from every 30?

**Comment by LuoweiZhou** [comment]
Hi @Anton-Velikodnyy, instead of sampling with [frame intervals](https://github.com/yjxiong/anet2016-cuhk/blob/721426622bd0d2d78df2e4443238e062471d46cd/pyActionRec/action_classifier.py#L108), we sample with [time intervals](https://github.com/yjxiong/anet2016-cuhk/blob/721426622bd0d2d78df2e4443238e062471d46cd/pyActionRec/video_proc.py#L85). This can be done by setting `timely=True, interval=0.5`, though be mindful the video is not sampled exactly at 0.5s (see [here](https://github.com/yjxiong/anet2016-cuhk/blob/721426622bd0d2d78df2e4443238e062471d46cd/pyActionRec/video_proc.py#L85) for the roundup). Due to this reason, the frame_to_second varies from video to video, as we have the precise formulation [here](https://github.com/salesforce/densecap/blob/master/data/anet_dataset.py#L131).

**Comment by LuoweiZhou** [comment]
One more change regarding this, we revise [this line](https://github.com/yjxiong/anet2016-cuhk/blob/721426622bd0d2d78df2e4443238e062471d46cd/pyActionRec/video_proc.py#L85) to `frame_interval = int(math.ceil(self._real_fps * interval))` such that the entire video could be covered. As a result, we need a `math.ceil` in our frame_to_second [formulation](https://github.com/salesforce/densecap/blob/master/data/anet_dataset.py#L131).
